# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mt_deck',
            fields=[
                ('f_card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('f_e1', models.CharField(max_length=100)),
                ('f_e2', models.CharField(max_length=100)),
                ('f_e3', models.CharField(max_length=100)),
                ('f_e4', models.CharField(max_length=100)),
                ('f_e5', models.CharField(max_length=100)),
                ('f_e6', models.CharField(max_length=100)),
                ('f_e7', models.CharField(max_length=100)),
                ('f_e8', models.CharField(max_length=100)),
                ('f_e1_size', models.IntegerField()),
                ('f_e2_size', models.IntegerField()),
                ('f_e3_size', models.IntegerField()),
                ('f_e4_size', models.IntegerField()),
                ('f_e5_size', models.IntegerField()),
                ('f_e6_size', models.IntegerField()),
                ('f_e7_size', models.IntegerField()),
                ('f_e8_size', models.IntegerField()),
            ],
            options={
                'ordering': ['f_card_no'],
            },
        ),
        migrations.CreateModel(
            name='mt_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_game_name', models.CharField(max_length=100)),
                ('f_game_size', models.IntegerField(default=2)),
                ('f_game_password', models.CharField(max_length=20)),
                ('f_player1', models.CharField(max_length=100)),
                ('f_player2', models.CharField(max_length=100)),
                ('f_player3', models.CharField(max_length=100)),
                ('f_p1_play_time', models.IntegerField(default=0)),
                ('f_p2_play_time', models.IntegerField(default=0)),
                ('f_p3_play_time', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['f_game_name'],
            },
        ),
    ]
