# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dob2', '0003_auto_20170913_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt_game',
            name='f_game_name',
            field=models.CharField(default='dgame', max_length=100),
        ),
        migrations.AlterField(
            model_name='mt_game',
            name='f_game_password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
