# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dob2', '0004_auto_20170913_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt_game',
            name='f_p1_stopped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_p2_stopped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_p3_stopped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_play',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_winner',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
