# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dob2', '0005_auto_20170915_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt_game',
            name='f_p1_cards_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_p2_cards_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_p3_cards_played',
            field=models.IntegerField(default=0),
        ),
    ]
