# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dob2', '0006_auto_20170915_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt_game',
            name='f_p1_waiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_p2_waiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mt_game',
            name='f_p3_waiting',
            field=models.IntegerField(default=0),
        ),
    ]
