# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dob2', '0009_auto_20170918_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='mt_iq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_game_name', models.CharField(default='dgame', max_length=100)),
                ('f_player', models.CharField(max_length=100)),
                ('f_time', models.DateTimeField(default=datetime.datetime.now)),
                ('f_play_time', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['f_game_name'],
            },
        ),
        migrations.CreateModel(
            name='mt_player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_player_name', models.CharField(default='player', max_length=100)),
                ('f_g_iq_avg_time', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('f_g_iq_best_time', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('f_g_iq_no_games', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['f_player_name'],
            },
        ),
    ]
